# Generated by Django 5.1.7 on 2025-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='Usuario',
            name='situacao',
            field=models.CharField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Pendente'), (3, 'Bloqueado')], default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='Usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[(0, 'Administrador'), (1, 'Representante de Município')], default=1, max_length=10),
        ),
    ]
