# Generated by Django 5.1.7 on 2025-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250516_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Pendente')], default=2, max_length=10),
        ),
    ]
