# Generated by Django 5.1.7 on 2025-04-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250516_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='municipios',
            field=models.ManyToManyField(blank=True, to='utils.municipio'),
        ),
    ]
