# Generated by Django 5.1.7 on 2025-04-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250516_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='municipios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.municipio'),
        ),
    ]
