# Generated by Django 5.1.7 on 2025-04-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250516_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='municipios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.municipio'),
        ),
    ]
