# Generated by Django 5.1.7 on 2025-04-24 13:43

from django.db import migrations
from django.contrib.auth import get_user_model


def create_dev_user(apps, schema_editor):
    Usuario = get_user_model()  # Obtém o modelo de usuário personalizado
    user = Usuario.objects.create_user(
        first_name="Desenvolvedor",
        username="exemplo@exemplo.com",
        email="exemplo@exemplo.com",
        password="123",
        tipo_usuario=0,
        situacao=0,
    )

    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20250516_5'),
    ]

    operations = [
        migrations.RunPython(create_dev_user),
    ]