# Generated by Django 5.2.1 on 2025-05-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250516_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Pendente')], default=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Representante de Município')], default=1),
        ),
    ]
