# Generated by Django 5.1.7 on 2025-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usuario_situacao_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Pendente')], default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Representante de Município')], default=1, max_length=10),
        ),
    ]