# Generated by Django 5.2.1 on 2025-05-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('ordem_bancaria', models.TextField()),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_estornado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('situacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluído'), ('Estornado Parcialmente', 'Estornado Parcialmente'), ('Estornado Totalmente', 'Estornado Totalmente')], max_length=30)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.settlement')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
    ]
