# Generated by Django 5.2.1 on 2025-05-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('codigo', models.CharField(max_length=100)),
                ('valor_custeio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_investimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField()),
                ('ciente', models.BooleanField(default=False)),
                ('data_ciencia', models.DateTimeField(blank=True, null=True)),
                ('sei_remocao_ciente', models.CharField(blank=True, max_length=100, null=True)),
                ('data_remocao_ciente', models.DateTimeField(blank=True, null=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.contabancaria')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.municipio')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.parlamentar')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'proposals',
            },
        ),
    ]
