# Generated by Django 5.2.1 on 2025-05-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='programa',
            new_name='project',
        ),
    ]
