# Generated by Django 5.2.1 on 2025-05-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_rename_programa_proposal_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='sei_remocao_ciente',
            new_name='processo_remocao_ciente',
        ),
    ]
