# Generated by Django 5.2.1 on 2025-05-16 15:21

import accountability.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_executado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('natureza_despesa', models.CharField(choices=[('investimento', 'Investimento'), ('custeio', 'Custeio')], max_length=50)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'verbose_name': 'Prestação de Contas',
                'verbose_name_plural': 'Prestação de Contas',
                'db_table': 'accountabilities',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caminho', models.FileField(upload_to=accountability.models.upload_to_accountability)),
                ('tamanho', models.IntegerField(blank=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('accountability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountability.accountability')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
            },
        ),
    ]
