# Generated by Django 5.2.1 on 2025-05-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountability',
            options={'verbose_name': 'Prestação de Contas', 'verbose_name_plural': 'Prestações de Contas'},
        ),
    ]
