# Generated by Django 5.2.1 on 2025-05-19 01:17

import accountability.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_alter_accountability_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_executado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('natureza_despesa', models.CharField(choices=[('investimento', 'Investimento'), ('custeio', 'Custeio')], max_length=50)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField()),
                ('version_date', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField(default=1)),
                ('current_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_versions', to='accountability.accountability')),
                ('version_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Prestação de Contas',
                'verbose_name_plural': 'Históricos de Prestação de Contas',
                'db_table': 'accountability_history',
                'ordering': ['-version_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caminho', models.FileField(upload_to=accountability.models.upload_to_accountability_history)),
                ('tamanho', models.IntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('original_document_id', models.IntegerField()),
                ('accountability_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accountability.accountabilityhistory')),
            ],
            options={
                'verbose_name': 'Histórico de Documento',
                'verbose_name_plural': 'Históricos de Documentos',
                'db_table': 'document_history',
            },
        ),
    ]
