# Generated by Django 5.2.1 on 2025-05-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(max_length=100, null=True, unique=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('cnpj', models.CharField(max_length=50, null=True, unique=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.IntegerField(blank=True, default=2025)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parlamentar',
                'verbose_name_plural': 'Parlamentares',
                'db_table': 'parlamentares',
            },
        ),
        migrations.CreateModel(
            name='PoliticaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Política Pública',
                'verbose_name_plural': 'Políticas Públicas',
                'db_table': 'politicas_publicas',
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=100, null=True)),
                ('conta', models.CharField(max_length=100, null=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.banco')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'db_table': 'contas_bancarias',
            },
        ),
    ]
